
# 新規配置（出庫・新たに走らせる）
dispatch:
  - station: B
    windows:
      - start: "05:00"
        end: "06:00"
        count: 2
        direction: up
        service: local  

  - station: F
    windows:
      - start: "05:30"
        end: "07:00"
        count: 2
        direction: up
        service: local  
