# constraints.yaml

# 単位はすべて「分」
board_min: 5               # 乗るのにかかる最低時間
post_hitch_ready_min: 15   # 便乗後に乗務できる最低時間

# 探索パラメータ（必要に応じて調整）
max_hops: 2                # 便乗の本数上限
window_min: 120            # 逆探索の時間窓
