# crew.yaml

# 時間帯ラベルの統一定義（ここを変えれば全配置に反映）
time_labels:
  am:
    start: "04:30"
    end: "08:00"
    signoff_limit: "13:00"  # この時間までに終点駅に着いていないとダメ
  pm:
    start: "11:30"
    end: "17:00"
    signoff_limit: "20:00"
  additional:
    start: "04:30"
    end: "20:00"
    signoff_limit: "20:00"

# 駅・時間帯ラベル・人数だけ
# 終点駅は連続している駅であることを前提に作ってます
placements:
  - station: A
    slot: am
    count: 5
    allowed_signoff: ["B"]

  - station: B
    slot: am
    count: 10
    allowed_signoff: ["B"]

  - station: D
    slot: am
    count: 5
    allowed_signoff: ["D"]

  - station: E
    slot: am
    count: 10
    allowed_signoff: ["D"]

  - station: F
    slot: am
    count: 5
    allowed_signoff: ["F"]

  - station: C
    slot: pm
    count: 10
    allowed_signoff: ["A", "B"]

  - station: E
    slot: pm
    count: 10
    allowed_signoff: ["D", "E"]

  - station: F
    slot: pm
    count: 5
    allowed_signoff: ["F"]



